base_drive: "/content/drive/MyDrive/Lyne"
train_jsonl: "dataset/train1.jsonl"
val_jsonl: "dataset/validation1.jsonl"
test_daily: "test-daily.xlsx"
valid_daily: "valid-daily.xlsx"
lora_folder: "finetuned_lora"
merged_folder: "model_final"
result_test: "resultats_test.xlsx"
eval_report: "evaluation.xlsx"